"""Convert real_world_dataset_dedup.hdf5 into a local LeRobotDataset (format v3.0, lerobot 0.4.4).

Run with the `lerobot` conda env (it has h5py):
    ~/miniconda3/envs/lerobot/bin/python claude_utility/convert_to_lerobot.py

- Reads the HDF5 read-only; never pushes to the Hub.
- fps = 30; timestamps are generated by LeRobot as frame_index / fps (orig_indices timing is not used).
- The last frame of each demo is dropped (its action is zero padding).
- Also writes meta/episode_source.json: episode_index -> HDF5 demo name and orig_demo_name.
"""
import argparse
import json
import os
import sys
import time

import h5py
import numpy as np
from lerobot.datasets.lerobot_dataset import LeRobotDataset

from paths import lerobot_data, raw

HERE = os.path.dirname(os.path.abspath(__file__))
H5 = raw('real_world_dataset_dedup.hdf5')          # defaults; override on the command line
OUT = lerobot_data()
REPO_ID = 'arthur/fan_grasp'
FPS = 30
TASK = 'pick up the fan by its handle'

def build_features(demo):
    """Feature spec taken from the data, so a different camera size or joint count still works."""
    h, w, c = demo['obs/real_rgb'].shape[1:]
    n_joints = demo['obs/real_joint_pos'].shape[1]
    return {
        'observation.images.wrist': {'dtype': 'video', 'shape': (h, w, c),
                                     'names': ['height', 'width', 'channels']},
        'observation.state': {'dtype': 'float32', 'shape': (n_joints + 1,),
                              'names': [f'joint_{i}' for i in range(n_joints)] + ['gripper']},
        'action': {'dtype': 'float32', 'shape': (demo['actions'].shape[1],),
                   'names': ['dx', 'dy', 'dz', 'drx', 'dry', 'drz', 'gripper']},
    }


def demo_names(d):
    return sorted([k for k in d.keys() if k.startswith('demo_')], key=lambda s: int(s.split('_')[1]))


def main():
    global H5, OUT, FPS, TASK, REPO_ID
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--input', default=H5, help='source HDF5 (default %(default)s)')
    ap.add_argument('--out', default=OUT, help='LeRobot dataset directory to create')
    ap.add_argument('--fps', type=int, default=FPS, help='one action per camera period (default %(default)s)')
    ap.add_argument('--task', default=TASK)
    ap.add_argument('--repo-id', default=REPO_ID)
    args = ap.parse_args()
    H5, OUT, FPS, TASK, REPO_ID = args.input, os.path.abspath(args.out), args.fps, args.task, args.repo_id
    if os.path.exists(OUT):
        sys.exit(f"{OUT} already exists; refusing to overwrite.")
    print(f"input {H5}\noutput {OUT}\nfps {FPS} | task '{TASK}' | repo_id {REPO_ID}\n")
    t0 = time.time()
    with h5py.File(H5, 'r') as f:
        d = f['data']
        names = demo_names(d)
        robot_type = str(d[names[0]].attrs['robot_name'])
        features = build_features(d[names[0]])
        print("features: " + ", ".join(f"{k} {tuple(v['shape'])}" for k, v in features.items()))
        ds = LeRobotDataset.create(repo_id=REPO_ID, fps=FPS, features=features, root=OUT,
                                   robot_type=robot_type, use_videos=True, image_writer_threads=4)
        source = []
        for ep, n in enumerate(names):
            g = d[n]
            rgb = g['obs/real_rgb'][:]                                   # one demo at a time
            state = np.concatenate([g['obs/real_joint_pos'][:], g['obs/gripper_cmd'][:][:, None]], axis=1).astype(np.float32)
            act = g['actions'][:].astype(np.float32)
            L = len(act)
            assert rgb.shape[0] == L and rgb.dtype == np.uint8 and state.shape[0] == L
            assert not np.abs(act[-1, :6]).any(), (n, 'last action row is not zero padding')
            for t in range(L - 1):                                       # drop the last (padding) frame
                ds.add_frame({'observation.images.wrist': rgb[t], 'observation.state': state[t],
                              'action': act[t], 'task': TASK})
            ds.save_episode()
            source.append({'episode_index': ep, 'hdf5_demo': n, 'orig_demo_name': str(g.attrs['orig_demo_name']),
                           'num_frames': L - 1})
            del rgb
            if (ep + 1) % 10 == 0 or ep + 1 == len(names):
                print(f"{ep + 1}/{len(names)} demos done  [{time.time() - t0:.0f}s]", flush=True)
        ds.finalize()
    with open(os.path.join(OUT, 'meta', 'episode_source.json'), 'w') as fp:
        json.dump(source, fp, indent=1)
    print(f"DONE in {time.time() - t0:.0f}s -> {OUT}")


if __name__ == '__main__':
    main()
